# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url: /
  class: QubitResourceRoute
  param:
    module: staticpage
    action: index
    slug: home

# --------------------------------------------------------- <QubitMetadataRoute>
# QubitMetadataRoute objects will generate and match URL to integrate the
# multiple metadata standards available.

slug;template:
  url: /:slug;:template
  class: QubitMetadataRoute
  param:
    action: index
    slug: { pattern: '[^;]+' }

slug:
  url: /:slug
  class: QubitMetadataRoute
  param:
    action: index

edit:
  url: /:slug/edit
  class: QubitMetadataRoute
  param:
    action: edit

copy:
  url: /:slug/copy
  class: QubitMetadataRoute
  param:
    action: copy

add:
  url: /:module/add
  class: QubitMetadataRoute
  param:
    action: edit

# -------------------------------------------------------- </QubitMetadataRoute>

informationobject/action:
  url: /:slug/:action
  class: QubitResourceRoute
  param:
    module: informationobject
    action: { pattern: 'addDigitalObject|fileList|multiFileUpload|reports' }

oai_harvester_harvest_all_sets:
  url: /oai/harvest/:type/:id
  param:
    module: qtOaiPlugin
    action: harvesterHarvest
    id: { pattern: \d+ }

oai_harvester_delete:
  url: /oai/deleteRepository/:repositoryId
  param:
    module: qtOaiPlugin
    action: harvesterDelete
    repositoryId: { pattern: \d+ }

oai_requests:
  url: /oai/request
  param:
    module: qtOaiPlugin
    action: oai

sword/action/slug:
  url: /sword/:action/:slug
  class: QubitResourceRoute
  param:
    module: qtSwordPlugin
    throw404: false

sword:
  url: /sword/:action
  param:
    module: qtSwordPlugin

# ------------------------------------------------------------------------------

slug;default_index:
  url:   /:slug;:module
  class: QubitResourceRoute
  param:
    action: index

slug/default:
  url: /:slug/:module/:action
  class: QubitResourceRoute

id/default:
  url: /:module/:action/id/:id
  class: QubitRoute

default_index:
  url: /:module
  param:
    action: index

default:
  url: /:module/:action
