# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    # content-type: text/html
    X-UA-Compatible: IE=edge,chrome=1
    viewport: width=device-width, initial-scale=1.0

  metas:
    title: AtoM
    description: Access to memory - Open information management toolkit
    # keywords: symfony, project
    # language: en
    # robots: index, follow

  stylesheets:
    # /plugins/sfDrupalPlugin/vendor/drupal/modules/system/system: { media: all, position: first }
    # /plugins/sfDrupalPlugin/vendor/drupal/modules/system/system-behavior: { media: all, position: first }
    # /plugins/sfDrupalPlugin/vendor/drupal/modules/system/system-menus: { media: all, position: first }
    # /plugins/sfDrupalPlugin/vendor/drupal/themes/garland/style: { media: all, position: first }
    # /plugins/sfDrupalPlugin/vendor/drupal/themes/garland/print: { media: print, position: first }
    # /vendor/yui/button/assets/skins/sam/button: { position: first }
    # /vendor/yui/menu/assets/skins/sam/menu: { position: first }
    # form:
    # graphic:
    # main:
    # print: { media: print, position: last }
    http://fonts.googleapis.com/css?family=Droid+Serif:400,400italic,700,700italic: { position: last }

  javascripts:
    /vendor/jquery:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/drupal:
    /vendor/yui/yahoo-dom-event/yahoo-dom-event:
    /vendor/yui/element/element-min:
    /vendor/yui/button/button-min:
    /vendor/yui/container/container_core-min:
    /vendor/yui/menu/menu-min:
    /vendor/modernizr:
    /vendor/jquery-ui:
    /vendor/jquery.expander.js:
    /vendor/jquery.imagesloaded.js:
    /vendor/jquery.masonry.js:
    /vendor/bootstrap/js/bootstrap:
    /vendor/chosen/chosen.jquery.js:
    qubit:
    dominion: { position: last }

  has_layout:     true
  layout:         layout

  components:
    header:       []
    sidebar:      []
    footer:       []
