indexSuccess:
  javascripts:
    blank:

advancedSuccess:
  stylesheets:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/ui/ui.all.css:
  javascripts:
    /js/advancedSearch.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/ui/ui.datepicker.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    multiRow:

globalReplaceSuccess:
  stylesheets:
  javascripts:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/jquery.once.js:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/collapse:
    /plugins/sfDrupalPlugin/vendor/drupal/misc/form:
    multiRow:
